Add License Key parameter
ant-media/Scripts pull request #205
Opened 2023-01-01 19:57 UTC by muratugureminoglu

2023-02-13 05:24 UTC, mekya commented
The expection from this development is like that
```
- if ANT_MEDIA_SERVER_ZIP_FILE is not specified {
    - if there is no license key {
       - Download and Install ant media server community through github
             #You can get the latest zip file with this command `$(curl -H "Accept: application/vnd.github+json" https://api.github.com/repos/ant-media/Ant-Media-Server/releases/latest | jq -r '.assets[0].browser_download_url')`
     }
     else if license key valid {
       - Download and install ant media server enterprise through the response of `check_license` 
     }
     else {
       - Exit the installation 
     }
}
else if ANT_MEDIA_SERVER_ZIP_FILE is specified {
   - Install
}
```

2023-02-13 05:25 UTC, mekya requested changes
Please take a look at the comment in the PR

2023-02-22 09:50 UTC, muratugureminoglu commented
> Please take a look at the comment in the PR

Thank you for your suggestion. A new commit has been sent.

2023-03-04 12:24 UTC, mekya requested changes
I've some comments. Could you please check it?

2023-03-04 12:24 UTC, mekya commented on .github/workflows/install-latest-to-ubuntu-20-04.yml
> +      - run: wget -O ant-media-server-community.zip "https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=io.antmedia&a=ant-media-server&v=LATEST&c=community&e=zip"
Why are we getting community edition in enterprise test?

2023-03-04 12:24 UTC, mekya commented on .github/workflows/install-latest-to-ubuntu-20-04.yml
> +      - run: wget https://raw.githubusercontent.com/ant-media/Scripts/4ce6a9b5fe7e1f226178d84d26e2883289e3c482/install_ant-media-server.sh && chmod 777 install_ant-media-server.sh
why don't we get from master branch or the branch having the same name?

There is a solution for this problem in travis side.
https://github.com/ant-media/Ant-Media-Server/blob/master/.travis.yml#L106

2023-03-04 12:26 UTC, mekya commented
Please check the sonatype-lift issues as well

2023-05-20 10:19 UTC, mekya approved these changes

2023-05-20 10:19 UTC, mekya approved these changes
Thank you. Good work

2023-05-20 10:23 UTC, mekya commented on install_ant-media-server.sh
> +  sed -i "$SED_COMPATIBILITY" 's/server.licence_key=.*/server.licence_key='$LICENSE_KEY'/' "$AMS_BASE/conf/red5.properties"
@sonatype ignoreall

2023-05-20 10:24 UTC, merged