Add supervisor to Dockerfile for process management
ant-media/Scripts pull request #322
Opened 2024-12-10 16:28 UTC by muratugureminoglu

2024-12-29 13:04 UTC, mekya requested changes
Hi @muratugureminoglu ,

I've some questions and I need some improvements.

Please check and let me know if you have any question or correct me if my requests are not feasible.

2024-12-29 13:04 UTC, mekya commented on docker/Dockerfile_Process
> +#RUN apt-get update && apt-get install -y supervisor
Please run these options with a parameter. You can use --build-arg or runtime parameters which one fits better. 

Please add some test deployment scripts to make sure that it's working as expected

2024-12-29 13:04 UTC, mekya commented on docker/Dockerfile_Process
> +#ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
Is it receiving the runtime parameters(-g, -s, etc.) as `start.sh`?

2025-01-06 07:47 UTC, muratugureminoglu commented on docker/Dockerfile_Process
> +#RUN apt-get update && apt-get install -y supervisor
Hi @mekya Thanks for your feedback. 

https://github.com/ant-media/Scripts/pull/322/files#diff-0c2fc70dc2b67872ee827354555425a2e03cb776b4b293b888a379a194420231R26


Workflow: https://github.com/ant-media/Scripts/blob/add-supervisor-support/.github/workflows/docker-test-supervisor.yml

2025-01-06 07:49 UTC, muratugureminoglu commented on docker/Dockerfile_Process
> +#ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
Yes,

https://github.com/ant-media/Scripts/blob/add-supervisor-support/docker/Dockerfile_Process#L107

2025-01-19 09:27 UTC, mekya approved these changes

2025-01-19 09:28 UTC, mekya commented
Thank you @muratugureminoglu for the test code and improvements 👏

2025-01-19 09:32 UTC, merged